version: "3.9"

services:
  database:
    image: postgres:alpine
    container_name: ebook_store_api_db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - database:/data/postgres
    networks:
      - services-network
networks:
  services-network:
    driver: bridge
volumes:
  database:
