openapi: 3.0.0
info:
  title: Ebook Store API
  description: Ebook Store API
  version: 1.0.0
tags:
  - name: authorization
    description: Authorization of API
  - name: categories
    description: Categories of ebooks
servers:
  - url: localhost:3000/
    description: Development server
paths:
  /sign_up:
    post:
      tags:
       - authorization
      summary: Sign Up
      description: Sign Up.
      operationId: signUp
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignUpResponse'
        400:
          description: Bab Request
        422:
          description: UnprocessableEntity
  /sign_in:
    post:
      tags:
       - authorization
      summary: Sign In
      description: Sign In.
      operationId: signIn
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignInResponse'
        401:
          description: Unauthorized
  /sign_out:
    delete:
      security:
        - Authorization: []
      tags:
       - authorization
      summary: Sign Out
      description: Sign Out.
      operationId: signOut
      responses:
        204:
          description: NoContent
  /categories:
    get:
      tags:
       - categories
      summary: Fetch categories
      description: Fetch categories.
      operationId: fetchCategories
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categories'
  /categories/{category_code}:
    put:
      security:
        - Authorization: []
      tags:
       - categories
      summary: Update category
      description: Updates a category.
      operationId: updateCategory
      parameters:
        - name: category_code
          in: path
          required: true
          description: Category code
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        204:
          description: No Content
        400:
          description: Bab Request
        404:
          description: Not Found
        422:
          description: UnprocessableEntity
    delete:
      security:
        - Authorization: []
      tags:
       - categories
      summary: Remove category
      description: Removes a category.
      operationId: removeCategory
      parameters:
        - name: category_code
          in: path
          required: true
          description: Category code
          schema:
            type: string
      responses:
        204:
          description: No Content
        404:
          description: Not Found
components:
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Categories:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: Id of category
              type:
                type: string
                description: Type of entity
              attributes:
                type: object
                properties:
                  name:
                    type: string
                    description: Name of category
                  code:
                    type: string
                    description: Code of category
        meta:
          type: object
          properties:
            total:
              type: integer
              description: Total of categories
        links:
          type: object
          properties:
            next:
              type: string
              description: Link to next page
      example:
        data:
          - id: "1"
            type: "category"
            attributes:
              name: "History"
              code: "history"
        meta:
          total: 21
        links:
          next: "/categories?page=2"
    Category:
      type: object
      properties:
        category:
          type: object
          properties:
            name:
              type: string
              description: Name of category
            code:
              type: string
              description: Code of category
    SignUpRequest:
      type: object
      properties:
        data:
          type: object
          properties:
            type:
              type: string
              description: Type of entity
            attributes:
              type: object
              properties:
                email:
                  type: string
                  description: User email
                password:
                  type: string
                  description: User password
      example:
        data:
            type: user
            attributes:
              email: user.test@gmail.com
              password: "123456"
    SignUpResponse:
      type: object
      properties:
        info:
          type: string
          description: Info message
      example:
        info: User created with success.
    SignInRequest:
      type: object
      properties:
        user:
          type: object
          properties:
            email:
              type: string
              description: User email
            password:
              type: string
              description: User password
      example:
        user:
          email: user.test@gmail.com
          password: "123456"
    SignInResponse:
      type: object
      properties:
        token:
          type: string
          description: JTW token
      example:
        info: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4Iiwic2NwIjoidXNlciIsImF1ZCI6bnVsbCwiaWF0IjoxNjIzODk5ODQyLCJleHAiOjE2MjM5MDM0NDIsImp0aSI6IjcxMzZhNzRhLTBjZTktNDIyMy1hMzFjLWU3NDhhZmU0MGUzNCJ9.oP9Ho5FZ44TeCT6687pDhBmUL-bWhHxCOuvd45_OJsg
